# Generated by Django 5.0.7 on 2025-09-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('employee_count', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('current_method', models.CharField(blank=True, choices=[('manual', 'Manual/Excel'), ('basic-software', 'Basic Software'), ('payroll-service', 'Payroll Service'), ('other', 'Other')], max_length=20)),
                ('primary_interest', models.CharField(choices=[('demo', 'Request Demo'), ('pricing', 'Get Pricing'), ('features', 'Learn Features'), ('implementation', 'Implementation Support')], max_length=20)),
                ('timeline', models.CharField(blank=True, choices=[('immediately', 'Immediately'), ('1-3-months', '1-3 months'), ('3-6-months', '3-6 months'), ('6-12-months', '6-12 months'), ('planning-stage', 'Just planning')], max_length=20)),
                ('budget_range', models.CharField(blank=True, choices=[('under-10k', 'Under KES 10,000'), ('10k-50k', 'KES 10,000 - 50,000'), ('50k-100k', 'KES 50,000 - 100,000'), ('100k+', 'Over KES 100,000')], max_length=20)),
                ('specific_needs', models.TextField(blank=True, help_text='Specific requirements or challenges')),
                ('newsletter', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('follow_up_date', models.DateTimeField(blank=True, help_text='When to follow up', null=True)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('demo-scheduled', 'Demo Scheduled'), ('proposal-sent', 'Proposal Sent'), ('negotiating', 'Negotiating'), ('closed-won', 'Closed - Won'), ('closed-lost', 'Closed - Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for follow-up')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submission_date'],
            },
        ),
    ]
