# Generated by Django 5.0.7 on 2025-09-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='kra_pin',
            field=models.CharField(blank=True, help_text='Company/Employer KRA PIN for tax purposes', max_length=20),
        ),
    ]
