# Generated by Django 5.0.7 on 2025-09-29 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('core', '0005_companysettings_kra_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='authtoken.token')),
            ],
            options={
                'verbose_name': 'Token Activity',
                'verbose_name_plural': 'Token Activities',
            },
        ),
    ]
