# Generated by Django 5.0.7 on 2025-10-11 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tokenactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company/Organization name', max_length=200)),
                ('subdomain', models.CharField(help_text="Unique subdomain for this tenant (e.g., 'acme' for acme.yourapp.com)", max_length=100, unique=True)),
                ('domain', models.CharField(blank=True, help_text='Custom domain (optional)', max_length=200, null=True)),
                ('subscription_plan', models.CharField(choices=[('trial', 'Trial (30 days)'), ('basic', 'Basic Plan'), ('professional', 'Professional Plan'), ('enterprise', 'Enterprise Plan')], default='trial', max_length=50)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('max_employees', models.IntegerField(default=10, help_text='Maximum number of employees allowed')),
                ('features_enabled', models.JSONField(default=dict, help_text='JSON object with enabled features')),
                ('billing_email', models.EmailField(help_text='Email for billing communications', max_length=254)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(blank=True, help_text='Primary admin user for this tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('hr_manager', 'HR Manager'), ('payroll_manager', 'Payroll Manager'), ('employee', 'Employee'), ('readonly', 'Read Only')], default='employee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant User',
                'verbose_name_plural': 'Tenant Users',
                'ordering': ['tenant__company_name', 'user__email'],
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
