# Generated by Django 5.0.7 on 2025-10-12 00:12

from django.db import migrations
from django.contrib.auth import get_user_model


def create_admin_users(apps, schema_editor):
    """Create admin users during migration"""
    User = get_user_model()
    
    # Create system admin
    if not User.objects.filter(email='admin@system.com').exists():
        user = User.objects.create_user(
            email='admin@system.com',
            first_name='System',
            last_name='Admin',
            is_staff=True,
            is_superuser=True,
            is_active=True
        )
        user.set_password('admin123')
        user.save()
        print(f"✅ Created system admin: admin@system.com")
    
    # Create primary admin 
    if not User.objects.filter(email='constantive@gmail.com').exists():
        user = User.objects.create_user(
            email='constantive@gmail.com',
            first_name='Admin',
            last_name='User',
            is_staff=True,
            is_superuser=True,
            is_active=True
        )
        user.set_password('September@2025.com')
        user.save()
        print(f"✅ Created primary admin: constantive@gmail.com")


def reverse_create_admin_users(apps, schema_editor):
    """Remove admin users during migration reverse"""
    User = get_user_model()
    User.objects.filter(email__in=['admin@system.com', 'constantive@gmail.com']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_tenantuser'),
    ]

    operations = [
        migrations.RunPython(create_admin_users, reverse_create_admin_users),
    ]
