# Generated by Django 5.0.7 on 2025-10-12 00:12

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_admin_users(apps, schema_editor):
    """Create admin users during migration"""
    User = apps.get_model('core', 'User')
    
    # Create system admin
    if not User.objects.filter(email='admin@system.com').exists():
        user = User(
            email='admin@system.com',
            first_name='System',
            last_name='Admin',
            is_staff=True,
            is_superuser=True,
            is_active=True,
            password=make_password('admin123')
        )
        user.save()
        print(f"✅ Created system admin: admin@system.com")
    else:
        # Update existing user password if needed
        user = User.objects.get(email='admin@system.com')
        user.password = make_password('admin123')
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save()
        print(f"✅ Updated system admin: admin@system.com")
    
    # Create primary admin 
    if not User.objects.filter(email='constantive@gmail.com').exists():
        user = User(
            email='constantive@gmail.com',
            first_name='Admin',
            last_name='User',
            is_staff=True,
            is_superuser=True,
            is_active=True,
            password=make_password('September@2025.com')
        )
        user.save()
        print(f"✅ Created primary admin: constantive@gmail.com")
    else:
        # Update existing user password if needed
        user = User.objects.get(email='constantive@gmail.com')
        user.password = make_password('September@2025.com')
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save()
        print(f"✅ Updated primary admin: constantive@gmail.com")


def reverse_create_admin_users(apps, schema_editor):
    """Remove admin users during migration reverse"""
    User = apps.get_model('core', 'User')
    User.objects.filter(email__in=['admin@system.com', 'constantive@gmail.com']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_tenantuser'),
    ]

    operations = [
        migrations.RunPython(create_admin_users, reverse_create_admin_users),
    ]
