# Generated by Django 5.0.7 on 2025-10-12 00:34

from django.db import migrations
from django.contrib.auth.hashers import make_password


def ensure_admin_passwords(apps, schema_editor):
    """Ensure admin user passwords are properly set"""
    User = apps.get_model('core', 'User')
    
    # Reset admin passwords to ensure they work
    try:
        admin_user = User.objects.get(email='admin@system.com')
        admin_user.password = make_password('admin123')
        admin_user.is_active = True
        admin_user.save()
        print(f"✅ Reset password for admin@system.com")
    except User.DoesNotExist:
        user = User(
            email='admin@system.com',
            first_name='System',
            last_name='Admin',
            is_staff=True,
            is_superuser=True,
            is_active=True,
            password=make_password('admin123')
        )
        user.save()
        print(f"✅ Created admin@system.com")
    
    try:
        primary_user = User.objects.get(email='constantive@gmail.com')
        primary_user.password = make_password('September@2025.com')
        primary_user.is_active = True
        primary_user.save()
        print(f"✅ Reset password for constantive@gmail.com")
    except User.DoesNotExist:
        user = User(
            email='constantive@gmail.com',
            first_name='Admin',
            last_name='User',
            is_staff=True,
            is_superuser=True,
            is_active=True,
            password=make_password('September@2025.com')
        )
        user.save()
        print(f"✅ Created constantive@gmail.com")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20251012_0312'),
    ]

    operations = [
        migrations.RunPython(ensure_admin_passwords),
    ]
