# Generated by Django 5.0.7 on 2025-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_monthly_insurance_premiums_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Account holder name as it appears on the bank account', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_type',
            field=models.CharField(blank=True, choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('fixed', 'Fixed Deposit Account')], help_text='Type of bank account', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(blank=True, help_text="Bank branch name (e.g., 'Westlands Branch')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_branch_code',
            field=models.CharField(blank=True, help_text="Specific branch code (e.g., '068')", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_code',
            field=models.CharField(blank=True, help_text="Central Bank assigned bank code (e.g., '68' for Equity Bank)", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, help_text="Full bank name (e.g., 'Equity Bank Kenya Limited')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_money_number',
            field=models.CharField(blank=True, help_text='Mobile money phone number (e.g., 0712345678)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa (Safaricom)'), ('airtel', 'Airtel Money'), ('tkash', 'T-Kash (Telkom)'), ('equitel', 'Equitel')], help_text='Mobile money service provider', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
    ]
