# Generated by Django 5.0.7 on 2025-09-27 21:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_monthly_insurance_premiums_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgenerationlog',
            name='report_type',
            field=models.CharField(choices=[('payslip', 'Payslip Report'), ('nssf', 'NSSF Report'), ('nhif', 'NHIF Report'), ('paye', 'PAYE Report'), ('p9', 'P9 Tax Report'), ('general', 'General Report')], max_length=50),
        ),
        migrations.CreateModel(
            name='P9Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField(help_text='Tax year for this P9 report', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2050)])),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('employer_pin', models.CharField(blank=True, help_text="Employer's KRA PIN", max_length=20)),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_main_name', models.CharField(blank=True, max_length=100)),
                ('employee_other_names', models.CharField(blank=True, max_length=100)),
                ('employee_pin', models.CharField(blank=True, help_text="Employee's KRA PIN", max_length=20)),
                ('total_basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column A - Total Basic Salary for the year', max_digits=12)),
                ('total_benefits_non_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column B - Total Benefits Non-Cash (company car, housing, etc.)', max_digits=12)),
                ('total_value_of_quarters', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column C - Value of accommodation provided by employer', max_digits=12)),
                ('total_gross_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column D - Total Gross Pay (A+B+C)', max_digits=12)),
                ('retirement_30_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column E1 - 30% of Basic Salary', max_digits=12)),
                ('retirement_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column E2 - Actual retirement contributions made', max_digits=12)),
                ('retirement_fixed_cap', models.DecimalField(decimal_places=2, default=Decimal('360000.00'), help_text='Column E3 - Fixed annual cap (KES 360,000)', max_digits=12)),
                ('total_ahl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column F - Affordable Housing Levy (1.5% of gross pay)', max_digits=12)),
                ('total_shif', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column G - Social Health Insurance Fund', max_digits=12)),
                ('total_prmf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column H - Post Retirement Medical Fund', max_digits=12)),
                ('total_owner_occupied_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column I - Owner Occupied mortgage interest', max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column J - Total allowable deductions', max_digits=12)),
                ('chargeable_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column K - Chargeable Pay (Gross Pay - Deductions)', max_digits=12)),
                ('tax_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column L - Tax charged on chargeable pay', max_digits=12)),
                ('total_personal_relief', models.DecimalField(decimal_places=2, default=Decimal('28800.00'), help_text='Column M - Personal Relief (KES 2,400 per month)', max_digits=12)),
                ('total_insurance_relief', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column N - Insurance Relief', max_digits=12)),
                ('total_paye_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Column O - PAYE Tax (Tax Charged - Personal Relief - Insurance Relief)', max_digits=12)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('issued', 'Issued to Employee'), ('submitted', 'Submitted to KRA')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this P9')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p9_reports', to='employees.employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'P9 Tax Report',
                'verbose_name_plural': 'P9 Tax Reports',
                'ordering': ['-tax_year', 'employee__user__first_name'],
                'unique_together': {('employee', 'tax_year')},
            },
        ),
        migrations.CreateModel(
            name='P9MonthlyBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('benefits_non_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('value_of_quarters', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('retirement_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ahl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('shif', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('prmf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('owner_occupied_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('chargeable_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('personal_relief', models.DecimalField(decimal_places=2, default=Decimal('2400.00'), max_digits=10)),
                ('insurance_relief', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paye_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('p9_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_breakdown', to='reports.p9report')),
            ],
            options={
                'verbose_name': 'P9 Monthly Breakdown',
                'verbose_name_plural': 'P9 Monthly Breakdowns',
                'ordering': ['p9_report', 'month'],
                'unique_together': {('p9_report', 'month')},
            },
        ),
    ]
