# Generated by Django 5.0.7 on 2025-09-28 10:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportgenerationlog_report_type_p9report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p9monthlybreakdown',
            name='retirement_30_percent_monthly',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='E1: 30% of Basic Salary', max_digits=10),
        ),
        migrations.AddField(
            model_name='p9monthlybreakdown',
            name='retirement_actual_monthly',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='E2: Actual contributions (NSSF + Pension)', max_digits=10),
        ),
        migrations.AddField(
            model_name='p9monthlybreakdown',
            name='retirement_fixed_monthly',
            field=models.DecimalField(decimal_places=2, default=Decimal('30000.00'), help_text='E3: Fixed amount (30,000)', max_digits=10),
        ),
    ]
